project:
  type: website
  render: 
    - "*qmd"
    - "!misc"
  output-dir: "docs"

website:
  title: "SABER 2023!"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

